// PM watchdog measurement — runs in CI every 6h, writes docs/PM-STATUS.md.
// No local session required. Truth comes from the DB, never a lane's report.
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const { execSync } = require('child_process');

const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);
const pct = (n, d) => (d ? Math.round((n / d) * 100) + '%' : '—');
const ago = (iso) => {
  if (!iso) return 'never';
  const h = (Date.now() - new Date(iso).getTime()) / 3.6e6;
  return h < 1 ? `${Math.round(h * 60)}m ago` : h < 48 ? `${Math.round(h)}h ago` : `${Math.round(h / 24)}d ago`;
};

(async () => {
  const out = [];
  const alerts = [];

  // ---- funnel (on-target proprietary leads) ----
  const { data: leads } = await db.from('leads').select('off_target, owner_name, owner_email, owner_phone, owner_linkedin, enrichment').limit(5000);
  const L = (leads || []).filter((l) => !l.off_target);
  const e = (l) => l.enrichment || {};
  const f = {
    n: L.length,
    pe: L.filter((l) => e(l).pe_owned === true || e(l).pe_owned === false).length,
    sized: L.filter((l) => e(l).size_estimate || e(l).est_revenue || (e(l).size_signals && Object.keys(e(l).size_signals || {}).length)).length,
    named: L.filter((l) => l.owner_name).length,
    reach: L.filter((l) => l.owner_email || l.owner_phone || l.owner_linkedin).length,
  };

  // ---- river guides ----
  const { data: rg } = await db.from('river_guides').select('name_status, exit_status, current_status_verified, contact, enrichment_status');
  // MERGE-AWARE (PM 8/5: "one number, both surfaces"). The 8/4 dedupe merged 20
  // duplicate people — rows KEPT for provenance, flagged not deleted. Counting
  // them double-counts the same human in EVERY metric, not just the total
  // (measured: total +20, named +18, verified +5, channel +9), and inflates
  // numerator and denominator at once so percentages are wrong both ways.
  // The dedupe tool always writes the contact.merged_into mirror, so this works
  // before and after migration 0025 without touching the select.
  const R = (rg || []).filter((r) => !(r.merged_into || r.contact?.merged_into));
  const ready = R.filter((r) => r.current_status_verified && r.exit_status === 'EXITED' && r.priority_band !== 'NURTURE' && (r.contact?.email || r.contact?.phone));

  // ---- serper runway ----
  const { data: cfg } = await db.from('app_config').select('key, value').in('key', ['serper_pack_credits', 'serper_pack_purchased_at']);
  const conf = Object.fromEntries((cfg || []).map((c) => [c.key, c.value]));
  let runway = 'unknown';
  if (conf.serper_pack_credits && conf.serper_pack_purchased_at) {
    const { data: used } = await db.from('usage_events').select('units').eq('service', 'serper').gte('at', conf.serper_pack_purchased_at);
    const spent = (used || []).reduce((s, r) => s + (Number(r.units) || 0), 0);
    const left = Number(conf.serper_pack_credits) - spent;
    const days = (Date.now() - new Date(conf.serper_pack_purchased_at).getTime()) / 864e5 || 1;
    const burn = spent / Math.max(days, 1);
    runway = `${left.toLocaleString()} credits left · ~${burn.toFixed(0)}/day · ~${burn > 0 ? Math.round(left / burn) : '∞'} days`;
    if (left < 5000) alerts.push(`SERPER LOW: ${left} credits left — top up $50/50k at serper.dev`);
    const expiry = new Date(new Date(conf.serper_pack_purchased_at).getTime() + 182 * 864e5);
    if (expiry - Date.now() < 30 * 864e5) alerts.push(`SERPER EXPIRING ${expiry.toISOString().slice(0, 10)} — credits lapse 6mo after purchase`);
  }

  // ---- deals needing attention ----
  const today = new Date().toISOString().slice(0, 10);
  const { data: deals } = await db.from('deals').select('name, stage, next_step_due').not('next_step_due', 'is', null).lte('next_step_due', today).neq('stage', 'Passed');
  for (const d of deals || []) alerts.push(`DEAL OVERDUE: ${d.name} (${d.stage}) — next step due ${d.next_step_due}`);

  // ---- feedback ----
  const { data: fb } = await db.from('feedback').select('id, author, body').in('status', ['submitted', 'triaged']);
  for (const x of fb || []) alerts.push(`FEEDBACK WAITING: ${x.author}: ${(x.body || '').slice(0, 60)}`);

  // ---- lane health (git) ----
  const lanes = ['lane/brokers', 'lane/frontend', 'lane/integrations'].map((b) => {
    try {
      const last = execSync(`git log origin/${b} -1 --format=%cI`, { encoding: 'utf8' }).trim();
      const ahead = execSync(`git rev-list --count origin/main..origin/${b}`, { encoding: 'utf8' }).trim();
      const hrs = (Date.now() - new Date(last).getTime()) / 3.6e6;
      if (hrs > 24) alerts.push(`LANE IDLE: ${b} last pushed ${ago(last)} — may need a restart paste (docs/RESTART-PROMPTS.md)`);
      return `- \`${b}\`: last push ${ago(last)}, ${ahead} unmerged`;
    } catch { return `- \`${b}\`: unreadable`; }
  });

  out.push('# PM STATUS (auto-generated by CI — no session required)');
  out.push(`_Refreshed ${new Date().toISOString()} · regenerated every 6h by .github/workflows/pm-watchdog.yml_`);
  out.push('');
  out.push(alerts.length ? '## 🚨 NEEDS ATTENTION\n' + alerts.map((a) => `- ${a}`).join('\n') : '## ✅ No alerts');
  out.push('');
  out.push('## Bulletproof-chain funnel (on-target proprietary leads)');
  out.push(`| step | now | target |`);
  out.push(`|---|---|---|`);
  out.push(`| PE-status determined | ${pct(f.pe, f.n)} | ≥95% |`);
  out.push(`| Sized | ${pct(f.sized, f.n)} | ≥90% |`);
  out.push(`| Owner named | ${pct(f.named, f.n)} | ≥80% |`);
  out.push(`| Owner contactable | ${pct(f.reach, f.n)} | ≥60% |`);
  out.push(`\n_n = ${f.n} leads_`);
  out.push('');
  out.push('## River guides');
  out.push(`- total ${R.length} · named ${R.filter((r) => r.name_status === 'RESOLVED').length} · verified ${R.filter((r) => r.current_status_verified).length} · with a channel ${R.filter((r) => r.contact?.email || r.contact?.phone || r.contact?.linkedin_url).length}`);
  out.push(`- **OUTREACH-READY (verified EXITED + channel): ${ready.length}**`);
  out.push(`- paid/VA queue: ${R.filter((r) => r.enrichment_status === 'NEEDS_PAID').length}`);
  out.push('');
  out.push(`## Serper runway\n- ${runway}`);
  out.push('');
  out.push('## Lanes\n' + lanes.join('\n'));

  fs.mkdirSync('docs', { recursive: true });
  fs.writeFileSync('docs/PM-STATUS.md', out.join('\n') + '\n');
  console.log(out.join('\n'));
})().catch((e) => { console.error('watchdog failed:', e.message); process.exit(1); });
